-- =============================================
-- JEJAK ATLET DATABASE SCHEMA
-- =============================================
-- Complete database schema for the Jejak Atlet fitness tracking application
-- Generated from existing Turso database structure
-- 
-- This schema supports:
-- - User management (trainers, athletes, admins, rekabytes-admin)
-- - Fitness component and test definitions
-- - Test result tracking and personal records
-- - Trainer-athlete enrollment relationships
-- - User management (trainers, athletes, admins, rekabytes-admin)
-- - Notification system
-- 
-- ADAPTED FOR SUPABASE (PostgreSQL)
-- =============================================

-- =============================================
-- CORE USER MANAGEMENT TABLES
-- =============================================

-- Main users table - stores all user accounts
-- Main users table - links to Supabase Auth
CREATE TABLE users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT,
    username TEXT,
    role TEXT NOT NULL CHECK (role IN ('athlete', 'trainer', 'admin', 'rekabytes-admin')),
    avatar_url TEXT,
    is_verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Extended detailed profile information (User Profiling)
CREATE TABLE user_profiling (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    phone TEXT,
    address TEXT,
    city TEXT,
    country TEXT,
    avatar_url TEXT,
    cover_image_url TEXT,
    date_of_birth DATE,
    gender TEXT,
    bio TEXT,
    social_links JSONB,
    preferences JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Extended trainer profiles
CREATE TABLE trainers (
    user_id UUID PRIMARY KEY,
    trainer_code TEXT NOT NULL UNIQUE,
    certification_id TEXT,
    specialization TEXT,
    verification_status TEXT DEFAULT 'pending' CHECK (verification_status IN ('pending', 'approved', 'rejected')),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Extended athlete profiles
CREATE TABLE athletes (
    user_id UUID PRIMARY KEY,
    sport TEXT NOT NULL,
    level TEXT DEFAULT 'beginner' CHECK (level IN ('beginner', 'intermediate', 'advanced', 'elite')),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- =============================================
-- FITNESS FRAMEWORK TABLES
-- =============================================

-- Fitness components (e.g., Cardio Endurance, Muscular Strength)
CREATE TABLE fitness_components (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Specific fitness tests within components
CREATE TABLE tests (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    component_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    unit TEXT,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    improvement_direction TEXT DEFAULT 'higher' CHECK (improvement_direction IN ('higher', 'lower')),
    FOREIGN KEY (component_id) REFERENCES fitness_components (id) ON DELETE CASCADE,
    UNIQUE(component_id, name)
);

-- =============================================
-- RELATIONSHIP AND DATA TABLES
-- =============================================

-- Trainer-athlete enrollment relationships
CREATE TABLE enrollments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    athlete_id UUID NOT NULL,
    trainer_id UUID NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMP,
    notes TEXT,
    viewed_at TIMESTAMP,
    accepting_at TIMESTAMP,
    FOREIGN KEY (athlete_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (trainer_id) REFERENCES users (id) ON DELETE CASCADE,
    UNIQUE(athlete_id, trainer_id)
);

-- Test results and performance tracking
CREATE TABLE test_results (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    athlete_id UUID NOT NULL,
    test_id INTEGER NOT NULL,
    result_value REAL,
    result_text TEXT,
    notes TEXT,
    test_date DATE NOT NULL,
    input_unit TEXT,
    is_best_record BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (athlete_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (test_id) REFERENCES tests (id) ON DELETE CASCADE
);

-- Athlete body metrics tracking
CREATE TABLE athlete_body_metrics (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    athlete_id UUID NOT NULL,
    measurement_date TEXT NOT NULL,
    weight REAL,
    height REAL,
    muscle_mass REAL,
    body_fat_percentage REAL,
    bmi REAL,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (athlete_id) REFERENCES users (id) ON DELETE CASCADE
);

-- User notifications
CREATE TABLE notifications (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    data TEXT, -- JSON data for additional context
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- =============================================
-- WORKOUT MANAGEMENT TABLES
-- =============================================

-- Workout templates created by trainers (MVP - simplified)
CREATE TABLE workout_templates (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    trainer_id UUID NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    synced_at TIMESTAMP,
    is_dirty BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (trainer_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Exercise library (MVP - system exercises only)
CREATE TABLE exercises (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    muscle_group TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    synced_at TIMESTAMP,
    is_dirty BOOLEAN DEFAULT FALSE
);

-- Exercises within a workout template (MVP - simplified)
CREATE TABLE workout_exercises (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workout_template_id INTEGER NOT NULL,
    exercise_id INTEGER NOT NULL,
    order_index INTEGER NOT NULL,
    sets INTEGER NOT NULL,
    reps INTEGER NOT NULL,
    rest_time INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    synced_at TIMESTAMP,
    is_dirty BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (workout_template_id) REFERENCES workout_templates (id) ON DELETE CASCADE,
    FOREIGN KEY (exercise_id) REFERENCES exercises (id) ON DELETE CASCADE
);

-- Workout assignments to athletes
CREATE TABLE workout_assignments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workout_template_id INTEGER NOT NULL,
    athlete_id UUID NOT NULL,
    trainer_id UUID NOT NULL,
    scheduled_date DATE NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'skipped', 'cancelled')),
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    synced_at TIMESTAMP,
    is_dirty BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (workout_template_id) REFERENCES workout_templates (id) ON DELETE CASCADE,
    FOREIGN KEY (athlete_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (trainer_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Athlete's progress through a workout session (MVP - simplified)
CREATE TABLE workout_session_progress (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workout_assignment_id INTEGER NOT NULL,
    workout_exercise_id INTEGER NOT NULL,
    set_number INTEGER NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    synced_at TIMESTAMP,
    is_dirty BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (workout_assignment_id) REFERENCES workout_assignments (id) ON DELETE CASCADE,
    FOREIGN KEY (workout_exercise_id) REFERENCES workout_exercises (id) ON DELETE CASCADE
);

-- =============================================
-- CALENDAR EVENT SYSTEM TABLES
-- =============================================

-- Event types for categorization
CREATE TABLE event_types (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    color TEXT NOT NULL DEFAULT '#3b82f6', -- Hex color for UI
    icon TEXT, -- Icon name for UI (e.g., 'trophy', 'calendar', 'flag')
    is_system BOOLEAN DEFAULT FALSE, -- System events cannot be deleted
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Main events table
CREATE TABLE events (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT,
    event_type_id INTEGER NOT NULL,
    created_by_user_id UUID NOT NULL, -- Trainer who created the event
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    location TEXT,
    address TEXT,
    max_participants INTEGER,
    registration_deadline TIMESTAMP,
    fee_amount REAL DEFAULT 0,
    fee_currency TEXT DEFAULT 'USD',
    status TEXT DEFAULT 'upcoming' CHECK (status IN ('draft', 'upcoming', 'ongoing', 'completed', 'cancelled')),
    is_public BOOLEAN DEFAULT FALSE, -- Public events visible to all athletes
    requires_approval BOOLEAN DEFAULT FALSE, -- Athletes need approval to join
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (event_type_id) REFERENCES event_types (id),
    FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Event participants (athletes assigned to events)
CREATE TABLE event_participants (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id INTEGER NOT NULL,
    athlete_id UUID NOT NULL,
    assigned_by_user_id UUID NOT NULL, -- Trainer who assigned the athlete
    status TEXT DEFAULT 'registered' CHECK (status IN ('invited', 'registered', 'confirmed', 'declined', 'attended', 'no_show', 'withdrawn')),
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    response_date TIMESTAMP,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    FOREIGN KEY (athlete_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_by_user_id) REFERENCES users (id) ON DELETE CASCADE,
    UNIQUE(event_id, athlete_id) -- Prevent duplicate assignments
);

-- Event reminders/notifications
CREATE TABLE event_reminders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id INTEGER NOT NULL,
    user_id UUID NOT NULL, -- Who will receive the reminder
    reminder_time TIMESTAMP NOT NULL, -- When to send the reminder
    message TEXT,
    is_sent BOOLEAN DEFAULT FALSE,
    sent_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Event results/performances (for competitions and tournaments)
CREATE TABLE event_results (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id INTEGER NOT NULL,
    athlete_id UUID NOT NULL,
    test_id INTEGER, -- Optional: link to fitness test if this is a competition
    result_value REAL,
    result_text TEXT,
    rank_position INTEGER,
    score REAL,
    notes TEXT,
    recorded_by_user_id UUID NOT NULL, -- Who recorded the result
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    FOREIGN KEY (athlete_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (test_id) REFERENCES tests (id),
    FOREIGN KEY (recorded_by_user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- =============================================
-- INDEXES FOR PERFORMANCE OPTIMIZATION
-- =============================================

-- User management indexes
CREATE INDEX idx_users_role ON users (role);
CREATE INDEX idx_users_created_at ON users (created_at);

-- Trainer indexes
CREATE INDEX idx_trainers_code ON trainers (trainer_code);
CREATE INDEX idx_trainers_verification ON trainers (verification_status);

-- Athlete indexes
CREATE INDEX idx_athletes_sport ON athletes (sport);
CREATE INDEX idx_athletes_level ON athletes (level);

-- Fitness framework indexes
CREATE INDEX idx_tests_component ON tests (component_id);
CREATE INDEX idx_tests_name ON tests (name);

-- Enrollment indexes
CREATE INDEX idx_enrollments_athlete ON enrollments (athlete_id);
CREATE INDEX idx_enrollments_trainer ON enrollments (trainer_id);
CREATE INDEX idx_enrollments_status ON enrollments (status);
CREATE INDEX idx_enrollments_requested_at ON enrollments (requested_at);

-- Test results indexes (critical for performance)
CREATE INDEX idx_test_results_athlete ON test_results (athlete_id);
CREATE INDEX idx_test_results_test ON test_results (test_id);
CREATE INDEX idx_test_results_date ON test_results (test_date);
CREATE INDEX idx_test_results_athlete_test ON test_results (athlete_id, test_id);
CREATE INDEX idx_test_results_best_record ON test_results (is_best_record) WHERE is_best_record = TRUE;
CREATE INDEX idx_test_results_created_at ON test_results (created_at);

-- Body metrics indexes
CREATE INDEX idx_athlete_body_metrics_athlete ON athlete_body_metrics (athlete_id);
CREATE INDEX idx_athlete_body_metrics_date ON athlete_body_metrics (measurement_date);

-- Notification indexes
CREATE INDEX idx_notifications_user ON notifications (user_id);
CREATE INDEX idx_notifications_type ON notifications (type);
CREATE INDEX idx_notifications_read ON notifications (is_read);
CREATE INDEX idx_notifications_created_at ON notifications (created_at);

-- Workout indexes
CREATE INDEX idx_workout_templates_trainer ON workout_templates (trainer_id);
CREATE INDEX idx_exercises_muscle_group ON exercises (muscle_group);
CREATE INDEX idx_workout_exercises_template ON workout_exercises (workout_template_id);
CREATE INDEX idx_workout_exercises_order ON workout_exercises (workout_template_id, order_index);
CREATE INDEX idx_workout_assignments_athlete ON workout_assignments (athlete_id);
CREATE INDEX idx_workout_assignments_trainer ON workout_assignments (trainer_id);
CREATE INDEX idx_workout_assignments_status ON workout_assignments (status);
CREATE INDEX idx_workout_assignments_date ON workout_assignments (scheduled_date);
CREATE INDEX idx_workout_session_progress_assignment ON workout_session_progress (workout_assignment_id);

-- Calendar event system indexes
CREATE INDEX idx_events_creator ON events (created_by_user_id);
CREATE INDEX idx_events_type ON events (event_type_id);
CREATE INDEX idx_events_dates ON events (start_date, end_date);
CREATE INDEX idx_events_status ON events (status);
CREATE INDEX idx_events_public ON events (is_public);
CREATE INDEX idx_events_location ON events (location);

-- Event participants indexes
CREATE INDEX idx_event_participants_event ON event_participants (event_id);
CREATE INDEX idx_event_participants_athlete ON event_participants (athlete_id);
CREATE INDEX idx_event_participants_assigned_by ON event_participants (assigned_by_user_id);
CREATE INDEX idx_event_participants_status ON event_participants (status);
CREATE INDEX idx_event_participants_registration ON event_participants (registration_date);

-- Event reminders indexes
CREATE INDEX idx_event_reminders_event ON event_reminders (event_id);
CREATE INDEX idx_event_reminders_user ON event_reminders (user_id);
CREATE INDEX idx_event_reminders_time ON event_reminders (reminder_time);
CREATE INDEX idx_event_reminders_sent ON event_reminders (is_sent);

-- Event results indexes
CREATE INDEX idx_event_results_event ON event_results (event_id);
CREATE INDEX idx_event_results_athlete ON event_results (athlete_id);
CREATE INDEX idx_event_results_rank ON event_results (rank_position);

-- =============================================
-- SUPABASE STORAGE & RLS SECURITY
-- =============================================

-- Create Avatars Bucket
INSERT INTO storage.buckets (id, name, public) 
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

-- Enable RLS on core tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiling ENABLE ROW LEVEL SECURITY;
ALTER TABLE trainers ENABLE ROW LEVEL SECURITY;
ALTER TABLE athletes ENABLE ROW LEVEL SECURITY;
ALTER TABLE enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- 1. Users & Profiling Policies
CREATE POLICY "Public profiles are viewable by everyone" ON users FOR SELECT USING (true);
CREATE POLICY "Users can update their own profile" ON users FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Public user profiling is viewable by everyone" ON user_profiling FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profiling" ON user_profiling FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own profiling" ON user_profiling FOR UPDATE USING (auth.uid() = user_id);

-- 2. Storage Policies (Avatars)
-- Allow public read access to avatars
CREATE POLICY "Avatar images are publicly accessible" 
ON storage.objects FOR SELECT 
USING ( bucket_id = 'avatars' );

-- Allow authenticated users to upload/update their own avatar
-- (Assuming folder structure: avatars/{user_id}/filename.png)
CREATE POLICY "Users can upload their own avatar" 
ON storage.objects FOR INSERT 
WITH CHECK ( 
    bucket_id = 'avatars' AND 
    auth.uid() = (storage.foldername(name))[1]::uuid 
);

CREATE POLICY "Users can update their own avatar" 
ON storage.objects FOR UPDATE 
USING ( 
    bucket_id = 'avatars' AND 
    auth.uid() = (storage.foldername(name))[1]::uuid 
);

CREATE POLICY "Users can delete their own avatar" 
ON storage.objects FOR DELETE 
USING ( 
    bucket_id = 'avatars' AND 
    auth.uid() = (storage.foldername(name))[1]::uuid 
);

-- =============================================
-- 3. EXTENDED RLS POLICIES (Fixes)
-- =============================================

-- Enable RLS on remaining tables
ALTER TABLE fitness_components ENABLE ROW LEVEL SECURITY;
ALTER TABLE tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE athlete_body_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE workout_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE workout_exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE workout_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE workout_session_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_reminders ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_results ENABLE ROW LEVEL SECURITY;

-- Trainers & Athletes
CREATE POLICY "Trainers are viewable by everyone" ON trainers FOR SELECT USING (true);
CREATE POLICY "Trainers can update own profile" ON trainers FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Athletes are viewable by everyone" ON athletes FOR SELECT USING (true);
CREATE POLICY "Athletes can update own profile" ON athletes FOR UPDATE USING (auth.uid() = user_id);

-- Enrollments
CREATE POLICY "Parties view own enrollments" ON enrollments FOR SELECT 
USING (auth.uid() = athlete_id OR auth.uid() = trainer_id);

CREATE POLICY "Athletes can request enrollment" ON enrollments FOR INSERT 
WITH CHECK (auth.uid() = athlete_id);

CREATE POLICY "Trainers can update enrollment status" ON enrollments FOR UPDATE 
USING (auth.uid() = trainer_id);

-- Notifications
CREATE POLICY "Users view own notifications" ON notifications FOR SELECT USING (auth.uid() = user_id);

-- Static Data (Read Only Public)
CREATE POLICY "Public view fitness components" ON fitness_components FOR SELECT USING (true);
CREATE POLICY "Public view tests" ON tests FOR SELECT USING (true);
CREATE POLICY "Public view exercises" ON exercises FOR SELECT USING (true);
CREATE POLICY "Public view event types" ON event_types FOR SELECT USING (true);

-- Test Results
CREATE POLICY "Athlete view own results" ON test_results FOR SELECT USING (auth.uid() = athlete_id);
CREATE POLICY "Trainer view student results" ON test_results FOR SELECT 
USING (
  EXISTS (
    SELECT 1 FROM enrollments 
    WHERE status = 'approved' 
    AND trainer_id = auth.uid() 
    AND athlete_id = test_results.athlete_id
  )
);
CREATE POLICY "Athlete record own result" ON test_results FOR INSERT WITH CHECK (auth.uid() = athlete_id);

-- Events
CREATE POLICY "Public events are viewable by everyone" ON events FOR SELECT 
USING (is_public = true OR created_by_user_id = auth.uid());

CREATE POLICY "Athletes view joined events" ON events FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM event_participants 
        WHERE event_id = events.id AND athlete_id = auth.uid()
    )
);

CREATE POLICY "Trainers manage own events" ON events FOR ALL 
USING (auth.uid() = created_by_user_id);

-- Event Participants
CREATE POLICY "View event participants" ON event_participants FOR SELECT 
USING (
    auth.uid() = athlete_id OR 
    EXISTS (SELECT 1 FROM events WHERE id = event_participants.event_id AND created_by_user_id = auth.uid())
);

